version: "3.8"

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - loki-grafana
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
      # - /home/aashis/docker-volumes/loki:/loki
    command: -config.file=/etc/loki/config.yaml

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - loki-grafana

networks:
  loki-grafana:
    driver: bridge