apiVersion: batch/v1
kind: Job
metadata: 
  name: porygon-request-job
spec:
  activeDeadlineSeconds: 600
  parallelism: {{PARALLELISM}}
  template:
    spec:
      containers:
      - name: porygon
        image: aashismhj/porygon:latest
        imagePullPolicy: Never
        command: ["python", "/app/script.py"]
        args: ["--url-index", "{{URL_INDEX}}"]
        envFrom:
        - configMapRef:
            name: shared-env-vars
      restartPolicy: Never
---