apiVersion: batch/v1
kind: Job
metadata: 
  name: porygon-job
spec:
  activeDeadlineSeconds: 300
  template:
    spec:
      container:
      - name: porygon
        image: porygon:latest
        command: ["python", "/app/script.py"]
        envFrom:
        - configMapRef:
            name: shared-env-vars
        restartPolicy: Never
    
---
